### ISSUE TITLE
Fails to build with libevent >= 2.1

### ISSUE THREAD

**Issue by jbeich** [xcllnt/openiked#11]
`_EVENT_VERSION` was renamed to `EVENT__VERSION` in libevent/libevent@68120d9b000a + libevent/libevent@f82c57e50531. Maybe switch to `LIBEVENT_VERSION` to be compatible with both.
```
checking libevent header version... not found
configure: error: libevent version header not found. -I/usr/local/include
[...]
conftest.c:188:32: error: use of undeclared identifier '_EVENT_VERSION'
        if ((rc = fprintf(fd ,"%s\n", _EVENT_VERSION)) <0)
                                      ^
```
See also https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=216527

**Comment by xcllnt** [comment]
Thanks. I think it's probably best to fully convert to libevent2...
